name: Rust CI
on:
  push:
    paths:
      - 'product/api/**'
  pull_request:
    paths:
      - 'product/api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cargo build and test
        working-directory: product
        run: |
          cargo build --workspace --locked
          cargo test --workspace --locked

